#those are the addresses of the scan_sha on the FPGA, I took them from Vivado when I mapped the modules on hw
SCAN_ADDR = [0x40000000,0x40010000,0x40020000,0x40030000]

#this info is retrievable in the drivers directory generated by vivado
ACTUAL = 0X10
GOLDEN = 0X40
TARG = 0X20
ACHASH= 0X60
HEAD = 0X80
